import { Header } from "@/components";
import { ClientProvider } from "@/providers";
import { getMessages, setRequestLocale } from "next-intl/server";
import "@/scss/app.css";
import stylesContainer from "@/scss/container.module.scss";
import { genralSans, jostGoogle, kontrap, beVietnamPro } from "@/utils";
import clsx from "clsx";
import { Footer } from "@/components";
import type { Metadata } from "next";
import React, { FunctionComponent, PropsWithChildren } from "react";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
type Props = {
  params: Promise<{ locale: string }>;
};
const RootLayout: FunctionComponent<PropsWithChildren<Props>> = async ({ params, children }) => {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale} className={`${genralSans.variable} ${kontrap.variable} ${jostGoogle.variable} ${beVietnamPro.variable}`}>
      <body>
        <ClientProvider locale={locale} messages={messages}>
          <div className={clsx([stylesContainer.container, "ml-auto", "mr-auto"])}>
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
        </ClientProvider>
      </body>
    </html>
  );
};
export default RootLayout;
